import { Product, Category, Banner } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Máy lạnh",
    slug: "may-lanh",
    icon: "❄️",
    description: "Máy lạnh inverter tiết kiệm điện, làm mát nhanh",
    productCount: 64,
    image: "/assets/dien-lanh/cat-may-lanh.png",
  },
  {
    id: "2",
    name: "Máy giặt",
    slug: "may-giat",
    icon: "🫧",
    description: "Máy giặt cửa trước, cửa trên, giặt sấy thông minh",
    productCount: 76,
    image: "/assets/dien-lanh/cat-may-giat.png",
  },
  {
    id: "3",
    name: "Tủ lạnh",
    slug: "tu-lanh",
    icon: "🧊",
    description: "Tủ lạnh inverter giữ tươi lâu, tiết kiệm điện",
    productCount: 58,
    image: "/assets/dien-lanh/cat-tu-lanh.png",
  },
  {
    id: "4",
    name: "Máy nước nóng",
    slug: "may-nuoc-nong",
    icon: "🚿",
    description: "Máy nước nóng trực tiếp, gián tiếp an toàn",
    productCount: 42,
    image: "/assets/dien-lanh/cat-may-nuoc-nong.png",
  },
];

export const banners: Banner[] = [
  {
    id: "1",
    title: "Điện Máy Lưu Thảo",
    subtitle: "Uy tín - chuyên nghiệp - nhanh chóng tại Long Xuyên",
    image: "/assets/dien-lanh/hero-dien-lanh.png",
    link: "/san-pham?filter=flash-sale",
    backgroundColor: "#0284c7",
  },
  {
    id: "2",
    title: "Mua bán - lắp đặt - bảo trì",
    subtitle: "Máy lạnh, tủ lạnh, máy giặt, máy nước nóng",
    image: "/assets/dien-lanh/cat-may-giat.png",
    link: "/danh-muc/may-giat",
    backgroundColor: "#168a74",
  },
  {
    id: "3",
    title: "Có thu máy cũ",
    subtitle: "Nhận đổi máy bù tiền, tư vấn qua Zalo 070.6767.921",
    image: "/assets/dien-lanh/cat-may-nuoc-nong.png",
    link: "/danh-muc/may-nuoc-nong",
    backgroundColor: "#e0f2fe",
  },
];

export const products: Product[] = [
  {
    id: "1",
    slug: "may-lanh-daikin-inverter-1hp-ftkb25xvmv",
    name: "Máy lạnh Daikin Inverter 1 HP FTKB25XVMV",
    brand: "Daikin",
    category: "Máy lạnh",
    categorySlug: "may-lanh",
    price: 9290000,
    originalPrice: 11990000,
    discount: 23,
    images: ["/assets/dien-lanh/product-may-lanh-1hp.png"],
    thumbnail: "/assets/dien-lanh/product-may-lanh-1hp.png",
    rating: 4.9,
    reviewCount: 846,
    sold: 2140,
    stock: 28,
    description:
      "Máy lạnh Daikin Inverter 1 HP phù hợp phòng dưới 15m², làm lạnh nhanh, vận hành êm và tiết kiệm điện cho gia đình.",
    shortDescription: "1 HP, Inverter, làm lạnh nhanh, phòng dưới 15m²",
    specs: {
      "Công suất": "1 HP",
      "Diện tích phù hợp": "Dưới 15m²",
      "Công nghệ": "Inverter tiết kiệm điện",
      "Tiện ích": "Làm lạnh nhanh, tự làm sạch",
      "Độ ồn": "Dàn lạnh 19 dB",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["may-lanh", "daikin", "inverter", "1hp"],
    isNew: true,
    isFeatured: true,
    isFlashSale: true,
    flashSaleEnd: "2026-12-31T23:59:59",
    installmentAvailable: false,
  },
  {
    id: "2",
    slug: "may-lanh-panasonic-inverter-1-5hp-xu12bkh",
    name: "Máy lạnh Panasonic Inverter 1.5 HP XU12BKH",
    brand: "Panasonic",
    category: "Máy lạnh",
    categorySlug: "may-lanh",
    price: 13990000,
    originalPrice: 16990000,
    discount: 18,
    images: ["/assets/dien-lanh/product-may-lanh-15hp.png"],
    thumbnail: "/assets/dien-lanh/product-may-lanh-15hp.png",
    rating: 4.8,
    reviewCount: 612,
    sold: 1580,
    stock: 24,
    description:
      "Máy lạnh Panasonic Inverter 1.5 HP cho phòng 15-20m², lọc khí tốt, làm lạnh sâu và giữ nhiệt ổn định.",
    shortDescription: "1.5 HP, lọc khí, phòng 15-20m²",
    specs: {
      "Công suất": "1.5 HP",
      "Diện tích phù hợp": "15-20m²",
      "Công nghệ": "Inverter, lọc khí nanoe",
      "Chế độ": "Làm lạnh nhanh, ngủ đêm",
      "Môi chất lạnh": "R32",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["may-lanh", "panasonic", "inverter", "1-5hp"],
    isNew: false,
    isFeatured: true,
    isFlashSale: false,
    installmentAvailable: false,
  },
  {
    id: "3",
    slug: "may-giat-lg-ai-dd-inverter-10kg",
    name: "Máy giặt LG AI DD Inverter 10 kg FV1410S4P",
    brand: "LG",
    category: "Máy giặt",
    categorySlug: "may-giat",
    price: 8990000,
    originalPrice: 11990000,
    discount: 25,
    images: ["/assets/dien-lanh/product-may-giat-10kg.png"],
    thumbnail: "/assets/dien-lanh/product-may-giat-10kg.png",
    rating: 4.8,
    reviewCount: 534,
    sold: 1890,
    stock: 18,
    description:
      "Máy giặt LG AI DD 10 kg nhận biết chất liệu vải, tối ưu chuyển động giặt và giảm rung ồn khi vận hành.",
    shortDescription: "10 kg, AI DD, Inverter, giặt hơi nước",
    specs: {
      "Khối lượng giặt": "10 kg",
      "Kiểu máy": "Cửa trước",
      "Công nghệ": "AI DD, Inverter",
      "Tiện ích": "Giặt hơi nước, hẹn giờ",
      "Tốc độ vắt": "1400 vòng/phút",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["may-giat", "lg", "inverter", "10kg"],
    isNew: true,
    isFeatured: true,
    isFlashSale: true,
    flashSaleEnd: "2026-12-31T23:59:59",
    installmentAvailable: false,
  },
  {
    id: "4",
    slug: "may-giat-samsung-ai-ecobubble-11kg",
    name: "Máy giặt Samsung AI EcoBubble 11 kg",
    brand: "Samsung",
    category: "Máy giặt",
    categorySlug: "may-giat",
    price: 10490000,
    originalPrice: 13990000,
    discount: 25,
    images: ["/assets/dien-lanh/product-may-giat-11kg.png"],
    thumbnail: "/assets/dien-lanh/product-may-giat-11kg.png",
    rating: 4.7,
    reviewCount: 428,
    sold: 1320,
    stock: 20,
    description:
      "Máy giặt Samsung AI EcoBubble 11 kg giặt sạch sâu bằng bong bóng siêu mịn, phù hợp gia đình đông người.",
    shortDescription: "11 kg, EcoBubble, AI Wash, cửa trước",
    specs: {
      "Khối lượng giặt": "11 kg",
      "Kiểu máy": "Cửa trước",
      "Công nghệ": "AI Wash, EcoBubble",
      "Tiện ích": "Vệ sinh lồng giặt, khóa trẻ em",
      "Tốc độ vắt": "1400 vòng/phút",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["may-giat", "samsung", "ecobubble", "11kg"],
    isNew: false,
    isFeatured: true,
    isFlashSale: false,
    installmentAvailable: false,
  },
  {
    id: "5",
    slug: "tu-lanh-lg-side-by-side-inverter-506l",
    name: "Tủ lạnh LG Side by Side Inverter 506L",
    brand: "LG",
    category: "Tủ lạnh",
    categorySlug: "tu-lanh",
    price: 14990000,
    originalPrice: 19990000,
    discount: 25,
    images: ["/assets/dien-lanh/product-tu-lanh-506l.png"],
    thumbnail: "/assets/dien-lanh/product-tu-lanh-506l.png",
    rating: 4.7,
    reviewCount: 386,
    sold: 960,
    stock: 14,
    description:
      "Tủ lạnh LG Side by Side 506L dung tích lớn, làm lạnh đa chiều, tiết kiệm điện và phù hợp gia đình 4-5 người.",
    shortDescription: "506L, Side by Side, Inverter, làm lạnh đa chiều",
    specs: {
      "Dung tích": "506 lít",
      "Kiểu tủ": "Side by Side",
      "Công nghệ": "Inverter, làm lạnh đa chiều",
      "Tiện ích": "Khử mùi, khay kính chịu lực",
      "Mức tiêu thụ": "Khoảng 1.25 kWh/ngày",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["tu-lanh", "lg", "side-by-side", "506l"],
    isNew: false,
    isFeatured: true,
    isFlashSale: true,
    flashSaleEnd: "2026-12-31T23:59:59",
    installmentAvailable: false,
  },
  {
    id: "6",
    slug: "tu-lanh-panasonic-prime-fresh-322l",
    name: "Tủ lạnh Panasonic Prime Fresh 322L",
    brand: "Panasonic",
    category: "Tủ lạnh",
    categorySlug: "tu-lanh",
    price: 10990000,
    originalPrice: 13990000,
    discount: 21,
    images: ["/assets/dien-lanh/product-tu-lanh-320l.png"],
    thumbnail: "/assets/dien-lanh/product-tu-lanh-320l.png",
    rating: 4.8,
    reviewCount: 302,
    sold: 820,
    stock: 16,
    description:
      "Tủ lạnh Panasonic 322L với ngăn đông mềm Prime Fresh, giữ thực phẩm tươi ngon và tiết kiệm thời gian rã đông.",
    shortDescription: "322L, Prime Fresh, Inverter, kháng khuẩn",
    specs: {
      "Dung tích": "322 lít",
      "Kiểu tủ": "Ngăn đá dưới",
      "Công nghệ": "Inverter, Prime Fresh",
      "Tiện ích": "Kháng khuẩn, khử mùi",
      "Mức tiêu thụ": "Khoảng 0.95 kWh/ngày",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["tu-lanh", "panasonic", "prime-fresh", "322l"],
    isNew: true,
    isFeatured: true,
    isFlashSale: false,
    installmentAvailable: false,
  },
  {
    id: "7",
    slug: "may-nuoc-nong-ariston-slim3-30l",
    name: "Máy nước nóng Ariston Slim3 30L",
    brand: "Ariston",
    category: "Máy nước nóng",
    categorySlug: "may-nuoc-nong",
    price: 3290000,
    originalPrice: 4590000,
    discount: 28,
    images: ["/assets/dien-lanh/product-may-nuoc-nong-30l.png"],
    thumbnail: "/assets/dien-lanh/product-may-nuoc-nong-30l.png",
    rating: 4.6,
    reviewCount: 214,
    sold: 740,
    stock: 32,
    description:
      "Máy nước nóng Ariston Slim3 30L thiết kế gọn, bình chứa bền, phù hợp phòng tắm gia đình cần nước nóng ổn định.",
    shortDescription: "30L, gián tiếp, chống giật ELCB, giữ nhiệt tốt",
    specs: {
      "Dung tích": "30 lít",
      "Loại máy": "Gián tiếp",
      "Công suất": "2500W",
      "An toàn": "ELCB chống giật, van an toàn",
      "Phù hợp": "Gia đình 3-5 người",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["may-nuoc-nong", "ariston", "30l", "gian-tiep"],
    isNew: false,
    isFeatured: true,
    isFlashSale: true,
    flashSaleEnd: "2026-12-31T23:59:59",
    installmentAvailable: false,
  },
  {
    id: "8",
    slug: "may-nuoc-nong-panasonic-truc-tiep-dh-4ns3vs",
    name: "Máy nước nóng Panasonic trực tiếp DH-4NS3VS",
    brand: "Panasonic",
    category: "Máy nước nóng",
    categorySlug: "may-nuoc-nong",
    price: 2490000,
    originalPrice: 3490000,
    discount: 29,
    images: ["/assets/dien-lanh/product-may-nuoc-nong-truc-tiep.png"],
    thumbnail: "/assets/dien-lanh/product-may-nuoc-nong-truc-tiep.png",
    rating: 4.7,
    reviewCount: 268,
    sold: 980,
    stock: 40,
    description:
      "Máy nước nóng trực tiếp Panasonic làm nóng nhanh, nhỏ gọn, có bơm trợ lực và nhiều lớp bảo vệ an toàn.",
    shortDescription: "Trực tiếp, bơm trợ lực, ELCB, làm nóng nhanh",
    specs: {
      "Loại máy": "Trực tiếp",
      "Công suất": "4500W",
      "Bơm trợ lực": "Có",
      "An toàn": "ELCB chống giật, cảm biến nhiệt",
      "Phù hợp": "Nhà có áp lực nước yếu",
      "Bảo hành": "24 tháng chính hãng",
    },
    tags: ["may-nuoc-nong", "panasonic", "truc-tiep", "bom-tro-luc"],
    isNew: true,
    isFeatured: true,
    isFlashSale: false,
    installmentAvailable: false,
  },
];

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
  }).format(price);
};

export const getProductsByCategory = (categorySlug: string): Product[] => {
  return products.filter((p) => p.categorySlug === categorySlug);
};

export const getFeaturedProducts = (): Product[] => {
  return products.filter((p) => p.isFeatured);
};

export const getFlashSaleProducts = (): Product[] => {
  return products.filter((p) => p.isFlashSale);
};

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find((p) => p.slug === slug);
};
